[incoming-sales]
strategy=rrmemory
timeout=20
retry=2
wrapuptime=8
ringinuse=no
autofill=yes
maxlen=0
servicelevel=20
monitor-type=MixMonitor
musicclass=travel-empire-hold
periodic-announce=custom/travel-empire/te-queue-periodic
periodic-announce-frequency=30
relative-periodic-announce=yes
announce-position=no
announce-holdtime=no
joinempty=yes
leavewhenempty=no
